### PR TITLE
(#17) win_chocolatey - Add TLS option for bootstrapping

### LINKED ISSUE #17: win_chocolatey - Allow users to select the TLS versions used for bootstrapping Chocolatey installation
Since February 3rd 2020, Chocolatey has disabled TLS 1.0 and 1.1 ([source](https://chocolatey.org/blog/remove-support-for-old-tls-versions)). Therefore, [this code](https://github.com/chocolatey/chocolatey-ansible/blob/2c5e7cfd5b501ccb0f028892b4f1031069163c8d/chocolatey/plugins/modules/win_chocolatey.ps1#L211-L215) that enables TLS 1.1 is at best unnecessary, and at worst silently leaves clients open to downgrade attacks.

### PR DESCRIPTION
**Pull request by vexx32**
## Description Of Changes

- Added `bootstrap_tls_version` option to `win_chocolatey`
- Added tests to verify that using a downgraded TLS version against the Community Repository would fail, as it requires a minimum of TLS 1.2

## Motivation and Context

Previously, the TLS configuration was set to allow both TLS 1.1 and TLS 1.2.

With this change, users can explicitly set the TLS versions they want to allow during bootstrapping. The default settings are to allow TLS 1.2 & 1.3, according to the TLS verisons available on the client.

This allows users who know the TLS versions of the servers their clients may need to communicate with to lock down the TLS versions being used to match, for example to avoid TLS downgrade attacks.

## Testing

1. Added tests to the win_chocolatey test targets
2. Exploratory testing of proposed changes
3. Will test in CI as well

## Change Types Made

* [ ] Bug fix (non-breaking change)
* [x] Feature / Enhancement (non-breaking change)
* [ ] Breaking change (fix or feature that could cause existing functionality to change)
* [ ] PowerShell code changes.

## Related Issue

Fixes #17

## Change Checklist

* [x] Requires a change to the documentation
* [x] Documentation has been updated
* [x] Tests to cover my changes, have been added
* [ ] All new and existing tests passed.
* [ ] PowerShell v2 compatibility checked.

### CODE REVIEW

**Comment by vexx32** [comment]
Marking this as draft till I have time to come back around and see what I broke with the tests.

**Comment by vexx32** [comment]
@Windos I believe this should be ready for review, tests are now working locally, so let's see how they do in CI.

**Review by Windos — DISMISSED** [review]
This LGTM and has tested successfully on my local machine

**Review by Windos — APPROVED** [review]
This still looks good (it just needed a rebase after merging the other PR)

**Pull request merged**
