### PR TITLE
(#169) Update ansible-core versions supported/tested

### LINKED ISSUE #169: Update CI checks and module metadata to reflect currently supported versions of `ansible-core`
### Checklist

- [x] I have verified this is the correct repository for opening this issue.
- [x] I have verified no other issues exist related to my request.

### Is Your Feature Request Related To A Problem? Please describe.

Per https://docs.ansible.com/ansible/latest/reference_appendices/release_and_maintenance.html#ansible-core-support-matrix Ansible-core 2.15 is EOL'd as of November, and we should add CI checks for 2.18 as well.

### Describe The Solution. Why is it needed?

- Update CI matrix in the Azure pipelines yaml to test against 2.16, 2.17, and 2.18
- Update minimum supported ansible-core version in `meta/runtime.yml`
- Update README to reflect supported/tested ansible-core versions

### Additional Context

_No response_

### Related Issues

_No response_

### PR DESCRIPTION
**Pull request by vexx32**
## Description Of Changes

- Set colleciton minimum ansible-core version to 2.16, the current lowest version that is still supported
- Update CI testing to test 2.16-2.18
- Build collection on 2.18 of ansible-core
- Update readme

## Motivation and Context

We need to keep in-step with Ansible's supported versions of ansible-core and ensure we're testing appropriately.

## Testing

Running tests in CI from the PR

### Operating Systems Testing

N/A

## Change Types Made

* [ ] Bug fix (non-breaking change).
* [x] Feature / Enhancement (non-breaking change).
* [ ] Breaking change (fix or feature that could cause existing functionality to change).
* [ ] Documentation changes.
* [ ] PowerShell code changes.

## Change Checklist

* [ ] Requires a change to the documentation.
* [x] Documentation has been updated.
* [ ] Tests to cover my changes, have been added.
* [ ] All new and existing tests passed?
* [ ] PowerShell code changes: PowerShell v3 compatibility checked?

## Related Issue

Fixes #169

### CODE REVIEW

**Review by Windos — APPROVED** [review]
This is looking good to me, thanks for putting it together @vexx32.

**Comment by Windos** [comment]
There was a test failure on this, but looking into it it looks like it was a connectivity issue with the Azure VM rather than with any changes to the collection. I have triggered a re-run (I'm not sure if it'll re-run the entire test suite or just the failure).

**Comment by Windos** [comment]
My re-run didn't work, pretty sure it didn't actually even start properly. This does now need a re-base, which should trigger the CI to run again in full.

**Comment by vexx32** [comment]
@Windos this has been rebased

**Comment by Windos** [comment]
Thanks again for sorting this out, @vexx32!

**Pull request merged**
