### PR TITLE
(maint) Update changelog for release v1.5.3

### PR DESCRIPTION
**Pull request by vexx32**
## Description Of Changes

- Update changelog for 1.5.3 release

Github release notes are here: https://github.com/chocolatey/chocolatey-ansible/releases/tag/untagged-7f518a4587cfd8a875c8

## Motivation and Context

Release needs a changelog

## Testing

Changelog only, also corrected some indentation from previous releases so it's all consistent.

### Operating Systems Testing

N/A

## Change Types Made

* [ ] Bug fix (non-breaking change).
* [ ] Feature / Enhancement (non-breaking change).
* [ ] Breaking change (fix or feature that could cause existing functionality to change).
* [x] Documentation changes.
* [ ] PowerShell code changes.

## Change Checklist

* [ ] Requires a change to the documentation.
* [x] Documentation has been updated.
* [ ] Tests to cover my changes, have been added.
* [ ] All new and existing tests passed?
* [ ] PowerShell code changes: PowerShell v3 compatibility checked?

## Related Issue

N/A

### CODE REVIEW

**Review by Windos — APPROVED** [review]

**Comment by Windos** [comment]
This looks good, thanks for putting this together @vexx32. I've turned on auto merge for when the pipeline finishes.

**Comment by mariolenz** [comment]
@vexx32 @Windos Not to put too fine a point on this, but dropping support for ansible-core < 2.15.0 might be considered a breaking and not only a documentation change.

For users, changing your requirements often _is_ breaking. Although I hope nobody is using 2.10 anymore, there *might* be people still using 2.14 even if it's unsupported. Anyway, I think it would have been better to drop the supported ansible-core version and do a new major (2.0.0) release. At the very least, I think this is worth a new minor release, but according to [SemVer](https://semver.org/) (which is a requirement for collections in the Ansible Community Package) I think a new major release would have been more appropriate.

ref #165

**Comment by vexx32** [comment]
@mariolenz our understanding from discussing with RedHat folks is that Ansible only enforces this as a warning and will not refuse to install or use the collection based on this metadata, so it will not break anything. It is simply reflective of what is tested and officially supported.

**Comment by mariolenz** [comment]
Possibly. Nevertheless, I think it's good practice to drop support for older versions of ansible-core (or any other requirements a collection might have) in major releases only. This is about semantic versioning, not about what Ret Hat folks tell you what works in practice ;-)

Don't get me wrong, this is just a suggestion. Actually, I think there are different opinions on dropping older versions of requirements. Personally, I prefer to do this only in major releases. And I don't think it would have hurt to release 2.0.0 instead of 1.5.3.

Please understand that this is just a friendly notice. If I've seen a real problem there on violating the [Ansible community package collections requirements](https://docs.ansible.com/ansible/latest/community/collection_contributors/collection_requirements.html), I'd have opened a new issue about this instead of just commenting here :smiley:

**Pull request merged**
