### PR TITLE
(#122) add version gates and split tests for choco v1

### LINKED ISSUE #122: Chocolatey CLI v2.x / v1.x compatibility
### Checklist

- [X] I have verified this is the correct repository for opening this issue.
- [X] I have verified no other issues exist related to my request.

### Is Your Feature Request Related To A Problem? Please describe.

Currently using some collection features results in less-than-ideal error states and we need to give everything a once-over to ensure that the way we're handling choco.exe is consistent with what works in v2.x as well as in v1.x of Chocolatey CLI.

### Describe The Solution. Why is it needed?

We will need to check the installed CLI version and have checks around:

- Using `--local-only` for `list` (can silently work in 2.x with `--limit-output` but for future-proofing we should just not use the parameter if not working with 1.x)
- Accepting `--allow-multiple` as a parameter (doesn't work in 2.x; we need to also update the module tests for this param to reflect that and cordon off some of these tests to be tested against choco v1.x only)

We should also review the existing tests to ensure there aren't any other v1.x specific behaviours that we're accounting for which need to be adjusted, or tests that need to be cordoned off to 1.x specific testing.

### Additional Context

_No response_

### Related Issues

_No response_

### PR DESCRIPTION
**Pull request by vexx32**
## Description Of Changes

- Split out allow_multiple tests into a new test file for choco v1.x specifically
- Add new allow_multiple test to verify the correct failure mode for allow_multiple
- Added helper function for getting the choco version
- Give a clear failure error for allow_multiple when using choco v2+

## Motivation and Context

Unsure if this is the way we want to go yet, but at least this is a decently clear illustration of what one option is here.

## Testing

1. Ran the tests locally
2. Running in CI

### Operating Systems Testing

N/A

## Change Types Made

* [ ] Bug fix (non-breaking change).
* [x] Feature / Enhancement (non-breaking change).
* [ ] Breaking change (fix or feature that could cause existing functionality to change).
* [ ] Documentation changes.
* [ ] PowerShell code changes.

## Change Checklist

* [ ] Requires a change to the documentation.
* [ ] Documentation has been updated.
* [x] Tests to cover my changes, have been added.
* [ ] All new and existing tests passed?
* [ ] PowerShell code changes: PowerShell v2 compatibility checked?

## Related Issue

Fixes #122

### CODE REVIEW

**Comment by Windos** [comment]
The `failed_when: not allow_multiple_cli_v2.failed` was doing the job of supressing the expected failure, but meant that the assertion after than was failing (because `failed_when` was flipping the failure to a success)

I've pushed a commit that swaps out the `failed_when` for simply ignoring errors, meaning the expected failure won't stop the playbook executing and the assertion can still test for the failure.

This has worked, in so far as the testing for that expected failure now passes, however it flows into other things that'll need to be in the v1 testing, specifically explicitly pinning an older version when two version are installed.

**Comment by Windos** [comment]
Mentioning this here as I'm not sure if we want to cover the syntax for v1.x under this PR or if I should split this off into its own issue/PR, but there are a number of instances of `choco list --local-only` in the tests.

I count 20 under `win_chocolatey/tasks/tests.yml`

There's also the decision around what to do with the module utils `Get-ChocolateyPackage` function, as it's a hard coded argument on the list command there.

**Comment by vexx32** [comment]
Hmm, all good points, thanks for pointing those out 🤔 

It would probably be simplest to do a breaking release at this point where v1.x of the collection supports CLI 1.x fully and v2.x of the collection supports CLI 2.x fully... there's gonna be a lot of changes needed either way, but that'll be much less finicky I think.

I'll have a look at doing that shortly, might best be in a different PR. Will figure out if we keep this one or not in a bit.

**Comment by vexx32** [comment]
@Windos I've split out additional tests to the choco v1 test file, and added some version gating where it looks appropriate. Additionally, tests _not_ in the v1 test file have had their `--local-only` params removed wherever they query chocolatey directly.

I skimmed through the other modules' tests, but didn't see anything that looks like it needs worrying about with the v2 changes.

**Comment by vexx32** [comment]
@Windos thanks for helping sort out the issues I was having here! 💜 

I've rebased this against the latest master and tidied up the commit history, I think this should be good for review (assuming CI passes, which I think it should).

**Review by Windos — APPROVED** [review]
Have read through this and all looks good to me.

It's now passing in the Azure pipeline, and I also tested locally against a Windows Server 2016 VM with success.

Nice work, @vexx32! 🎉

**Pull request merged**
