### PR TITLE
(maint) Add templates and supporting docs

### PR DESCRIPTION
**Pull request by pauby**
Added the following:

* Issue template
* Feature request template
* Pull request template
* Security disclosure template (for consistency)
* Update README with contributing info
* CONTRIBUTING guide

Most of this was taken from the [choco](https://github.com/chocolatey/choco) repository.

@vexx32 this is in draft, however can you review in preparation for it coming out of draft?

### CODE REVIEW

**Comment by vexx32** [comment]
@pauby is this one still needed anymore, since we added templates to the organisational `.github` repo?

**Comment by pauby** [comment]
I don't think so. However, can we leave it here, and I'll ensure that any of the changes suggested are in the .github files?

I'll close it when done.

**Review by vexx32 — COMMENTED** [review]
The rest seems fine here, not sure the best way to capture everything for this repo though 🤔

**Comment by vexx32** [comment]
@pauby is this still needed? I think this is somewhat covered by the global templates now, isn't it?

**Comment by pauby** [comment]
Good catch. This is no longer needed. I'll close it.

**Pull request closed without merging**
